spring.application.name=backend
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d75k9ooule4c73cshkgg-a:5432/college_attendance_db_uz5r}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:college_attendance_db_uz5r_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:IsHojb9VmN8gfB7yd0Jif2f81vkjpkEQ}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=86400000

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

gemini.api.key=AIzaSyBpMB2Lk-S1SrQQZMcZY2VHEugt6BH4TC0
